# Salidas tabulares de consultas principales

Este cuaderno ejecuta 15 consultas analíticas y muestra sus resultados en tablas (DataFrames) para facilitar validación y revisión de datos.

In [10]:
from pathlib import Path
import subprocess
import tempfile

import pandas as pd
from IPython.display import display

DB_PATH = "localhost:/Users/wilsonjonatan/Documents/bases 1 2026/violencia guate/sql/db/violencia_guate.fdb"
DB_USER = "sysdba"
DB_PASSWORD = "masterkey"
ISQL_PATH = "/Library/Frameworks/Firebird.framework/Resources/bin/isql"

In [11]:
def run_query(sql: str) -> pd.DataFrame:
    query = sql.strip().rstrip(";") + ";"
    script = f"SET HEADING OFF;\nSET LIST ON;\n{query}\n"

    with tempfile.NamedTemporaryFile("w", suffix=".sql", delete=False, encoding="utf-8") as tmp:
        tmp.write(script)
        tmp_path = tmp.name

    try:
        result = subprocess.run(
            [ISQL_PATH, "-user", DB_USER, "-password", DB_PASSWORD, DB_PATH, "-q", "-i", tmp_path],
            capture_output=True,
            text=True,
        )
    finally:
        Path(tmp_path).unlink(missing_ok=True)

    output = "\n".join(part for part in (result.stdout, result.stderr) if part)
    rows = []
    current = {}

    for raw_line in output.splitlines():
        line = raw_line.strip()
        if not line:
            if current:
                rows.append(current)
                current = {}
            continue
        if line.startswith("SQL>") or line.startswith("DatabaseError") or line.startswith("Warning"):
            continue

        parts = line.split(None, 1)
        if len(parts) == 2:
            key, value = parts
            current[key.lower()] = value.strip()

    if current:
        rows.append(current)

    df = pd.DataFrame(rows)
    for column in df.columns:
        numeric = pd.to_numeric(df[column], errors="coerce")
        if len(df[column]) > 0 and numeric.notna().all():
            df[column] = numeric
    return df


def show_table(df: pd.DataFrame, titulo: str, max_rows: int = 200) -> None:
    print(f"\n{titulo}")
    print("-" * len(titulo))
    if df.empty:
        print("Sin datos para mostrar.")
        return
    print(f"Filas totales: {len(df)}")
    display(df.head(max_rows))
    if len(df) > max_rows:
        print(f"Mostrando primeras {max_rows} filas de {len(df)}.")

In [12]:
# Ejecutar las 30 consultas propuestas en el mismo orden del archivo SQL
import re

sql_file = Path("/Users/wilsonjonatan/Documents/bases 1 2026/violencia guate/sql/consultas_propuestas.sql")
contenido = sql_file.read_text(encoding="utf-8")

patron = re.compile(
    r"/\*\s*(\d+)\)\s*(.*?)\*/\s*(.*?);(?=\s*/\*|\s*$)",
    re.S,
 )

consultas = []
for numero, titulo, sql in patron.findall(contenido):
    consultas.append((int(numero), titulo.strip(), sql.strip()))

consultas = sorted(consultas, key=lambda x: x[0])

print(f"Consultas detectadas: {len(consultas)}")

for numero, titulo, sql in consultas:
    df = run_query(sql)
    show_table(df, f"{numero}) {titulo}")

Consultas detectadas: 30

1) LISTA: Cantidad de homicidios por anio y departamento
--------------------------------------------------------
Filas totales: 289

     anio    departamento  total_homicidios
0    2023       Guatemala             20352
1    2023         Jutiapa              9042
2    2023  Quetzaltenango              6038
3    2023       Escuintla              4405
4    2023          Jalapa              3334
..    ...             ...               ...
195  2016      Retalhuleu                 4
196  2016   Huehuetenango                 4
197  2016  Quetzaltenango                 4
198  2014      San Marcos                 4
199  2014    Sacatepéquez                 4

[200 rows x 3 columns]

Mostrando primeras 200 filas de 289.

2) LISTA/PARCIAL: Denuncias por violencia contra la mujer por municipio
-----------------------------------------------------------------------
Filas totales: 15

,departamento,municipio,total_denuncias,clasificacion_delito,delito
0,Alta Verapaz,Cobán,888,Violencia contra la mujer,Violencia contra la mujer
1,Alta Verapaz,San Pedro Carchá,250,Violencia contra la mujer,Violencia contra la mujer
2,Alta Verapaz,San Cristóbal Verapaz,180,Violencia contra la mujer,Violencia contra la mujer
3,Alta Verapaz,Fray Bartolomé de Las Casas,100,Violencia contra la mujer,Violencia contra la mujer
4,Alta Verapaz,Raxruhá,81,Violencia contra la mujer,Violencia contra la mujer
5,Alta Verapaz,Chahal,76,Violencia contra la mujer,Violencia contra la mujer
6,Alta Verapaz,Chisec,74,Violencia contra la mujer,Violencia contra la mujer
7,Alta Verapaz,Santa Cruz Verapaz,71,Violencia contra la mujer,Violencia contra la mujer
8,Alta Verapaz,Tactic,57,Violencia contra la mujer,Violencia contra la mujer
9,Alta Verapaz,San Juan Chamelco,39,Violencia contra la mujer,Violencia contra la mujer
10,Alta Verapaz,Lanquín,28,Violencia contra la mujer,Violencia contra la mujer
11,Alta Verapaz,Panzós,24,Violencia contra la mujer,Violencia contra la mujer
12,Alta Verapaz,Senahú,11,Violencia contra la mujer,Violencia contra la mujer
13,Alta Verapaz,Tamahú,8,Violencia contra la mujer,Violencia contra la mujer
14,Alta Verapaz,Tucurú,5,Violencia contra la mujer,Violencia contra la mujer

3) LISTA: Top 5 tipos de hechos delictivos en ultimos 5 anios
-------------------------------------------------------------
Filas totales: 5

  clasificacion_delito             delito  total_casos
0                Otros              Otros       765708
1             Amenazas           Amenazas       308913
2            Extorsión          Extorsión       211323
3       Lesiones leves     Lesiones leves       130840
4    Lesiones culposas  Lesiones culposas       128128

4) LISTA: Sentencias dictadas por tipo de delito y anio
-------------------------------------------------------
Filas totales: 539

     anio                                             delito  total_sentencias
0    2008                          Violencia contra la mujer                 2
1    2009                          Violencia contra la mujer                67
2    2009                          VIOLENCIA CONTRA LA MUJER                18
3    2010                          Violencia contra la mujer               209
4    2010                          VIOLENCIA CONTRA LA MUJER                77
..    ...                                                ...               ...
195  2018  VIOLENCIA CONTRA LA MUJER EN SU MANIFESTACIÓN ...                 1
196  2018  VIOLENCIA CONTRA LA MUJER EN SU MANIFESTACIÓN ...                 1
197  2018  VIOLENCIA CONTRA LA MUJER EN SU MANIFESTACIÓN ...                 1
198  2018  VIOLENCIA CONTRA LA MUJER EN SU MANIFESTACIÓN ...                 1
199  2018  VIOLENCIA CONTRA LA MUJER EN SU MANIFESTACIÓN ...                 1

[200 rows x 3 columns]

Mostrando primeras 200 filas de 539.

5) PARCIAL: Promedio de edad de victimas de violencia intrafamiliar
-------------------------------------------------------------------
Filas totales: 1

   promedio_edad_victima
0                  32.96

6) PARCIAL: Distribucion de embarazos adolescentes por region
-------------------------------------------------------------
Sin datos para mostrar.

7) PARCIAL: Casos de violencia infantil relacionados con trabajo infantil
-------------------------------------------------------------------------
Sin datos para mostrar.

8) LISTA: Porcentaje de denuncias por discriminacion segun etnia
----------------------------------------------------------------
Filas totales: 6

  grupo_etnico  total_casos  porcentaje
0         Maya           85        75.2
1     Garífuna           23        20.3
2        Xinka            2         1.7
3        XINCA            1         0.8
4      K'Iche'            1         0.8
5     Q'Qechi'            1         0.8

9) LISTA/PARCIAL: Comparativa escolaridad vs tipo de falta judicial
-------------------------------------------------------------------
Filas totales: 35

   nivel_escolaridad             tipo_falta  total_casos
0           Primaria  Las buenas costumbres         2962
1           Primaria           Las personas         2119
2           Primaria                  Otras         1499
3             Básico  Las buenas costumbres         1286
4             Básico                  Otras          928
5           Primaria          Orden público          810
6      Diversificado  Las buenas costumbres          785
7             Básico           Las personas          784
8           Ignorado           Las personas          746
9      Diversificado                  Otras          742
10           Ninguno  Las buenas costumbres          630
11           Ninguno           Las personas          518
12            Básico          Orden público          509
13     Diversificado           Las personas          504
14     Diversificado          Orden público          429
15          Primaria           La propiedad          395
16       Preprimaria  Las buenas costumbres          317
17           Ninguno                  Otras          238
18       Preprimaria           Las personas          197
19       Preprimaria                  Otras          176
20            Básico           La propiedad          163
21          Ignorado  Las buenas costumbres          147
22           Ninguno          Orden público          138
23          Ignorado                  Otras          134
24           Ninguno           La propiedad          109
25       Preprimaria          Orden público          108
26          Superior                  Otras          102
27     Diversificado           La propiedad           81
28          Ignorado           La propiedad           77
29          Superior  Las buenas costumbres           74
30          Ignorado          Orden público           67
31          Superior          Orden público           49
32          Superior           Las personas           44
33       Preprimaria           La propiedad           32
34          Superior           La propiedad            9

10) LISTA: Numero de necropsias por anio
----------------------------------------
Sin datos para mostrar.

11) LISTA: Tasa de violencia estructural procesadas vs no procesadas
--------------------------------------------------------------------
Filas totales: 1

  estado_proceso  total  porcentaje
0   NO_PROCESADA    113       100.0

12) PARCIAL: Relacion tipo de empleo y ocurrencia de hechos delictivos
----------------------------------------------------------------------
Filas totales: 11

                  ocupacion  total_hechos
0             NO_ESPECIFICA            10
1                   ALBANIL             1
2                   MAESTRO             1
3                  MECANICO             1
4                  GANADERO             1
5                  CUIDADOR             1
6                AGRICULTOR             1
7                ESTUDIANTE             1
8               COMERCIANTE             1
9               AMA_DE_CASA             1
10  TRABAJADOR_DE_SERVICIOS             1

13) LISTA/PARCIAL: Casos VCM con sentencia firme
------------------------------------------------
Filas totales: 17

    anio  total_casos
0   2008            2
1   2009           79
2   2010          263
3   2011          518
4   2012          822
5   2013         1639
6   2014         2449
7   2015         3163
8   2016         3478
9   2017         3410
10  2018         3433
11  2019         3722
12  2020         1759
13  2021         3910
14  2022         4301
15  2023         4736
16  2024          407

14) PARCIAL: Idiomas hablados por victimas de discriminacion
------------------------------------------------------------
Filas totales: 16

        idioma  total_victimas
0    Kaqchikel              29
1      K'iche'              28
2     Garífuna              17
3     Q'eqchi'              12
4          Mam               9
5     Q'qechi'               4
6       K'iché               3
7   Q'anjob'al               3
8         Ixil               1
9        Xinka               1
10     Ki'che'               1
11      K´iche               1
12    Ch'orti'               1
13    Poqomch'               1
14   Jakalteka               1
15   Tz'utujil               1

15) PARCIAL: Numero de personas por hogar en casos VIF
------------------------------------------------------
Filas totales: 1

  promedio_personas_por_hogar
0                      <null>

16) PARCIAL: Tasa de violencia infantil escolarizada vs no escolarizada
-----------------------------------------------------------------------
Filas totales: 1

  condicion_escolar  total_casos  porcentaje
0      ESCOLARIZADA          250       100.0

17) PARCIAL: Casos de trabajo infantil por sector economico
-----------------------------------------------------------
Sin datos para mostrar.

18) PARCIAL: Relacion edad y tipo de violencia sufrida
------------------------------------------------------
Filas totales: 24

,tipo_violencia,subtipo_violencia,edad_promedio,edad_minima,edad_maxima,total_registros
0,ESTRUCTURAL,Étnica,41.93,21,67,75
1,ESTRUCTURAL,Racial,38.76,23,61,25
2,ESTRUCTURAL,Discriminación,32.85,15,58,7
3,ESTRUCTURAL,Racial y Étnica,24.00,20,28,2
4,ESTRUCTURAL,Discriminación Étnica,34.00,34,34,1
5,ESTRUCTURAL,Étnica racial,45.00,45,45,1
6,ESTRUCTURAL,Étnica laboral,45.00,45,45,1
7,ESTRUCTURAL,Étnica/ Género,59.00,59,59,1
8,NINEZ,Embarazo en menor de 14 años,13.00,13,13,214
9,NINEZ,Violencia física y psicológica,12.00,12,12,17
10,NINEZ,Acoso escolar (bullying),12.00,12,12,9
11,NINEZ,Racismo y discriminación,12.00,12,12,4
12,NINEZ,Acoso y hostigamiento sexual,12.00,12,12,4
13,NINEZ,Abuso de autoridad,12.00,12,12,2
14,VIF,TIPAGRE_2122,35.75,7,99,434
15,VIF,TIPAGRE_1122,31.55,9,99,361
16,VIF,TIPAGRE_1222,33.15,13,99,109
17,VIF,TIPAGRE_2121,35.34,17,79,23
18,VIF,TIPAGRE_2212,18.95,3,99,20
19,VIF,TIPAGRE_1121,26.52,16,54,19
20,VIF,TIPAGRE_2112,15.70,7,44,17
21,VIF,TIPAGRE_2221,24.14,6,50,7
22,VIF,TIPAGRE_1112,32.50,30,35,2
23,VIF,TIPAGRE_2111,15.00,15,15,1

19) PARCIAL: Desnutricion aguda por departamento, municipio y anio
------------------------------------------------------------------
Sin datos para mostrar.

20) PARCIAL: Retardo en desarrollo por grupo etario, sexo y region
------------------------------------------------------------------
Sin datos para mostrar.

21) PARCIAL: Incidencia cronicas por CIE-10
-------------------------------------------
Sin datos para mostrar.

22) PARCIAL: Evolucion dengue y dengue grave 2012-2024
------------------------------------------------------
Sin datos para mostrar.

23) PARCIAL: Malaria por grupo etario y sexo municipal
------------------------------------------------------
Sin datos para mostrar.

24) PARCIAL: Desnutricion infantil vs violencia intrafamiliar por departamento
------------------------------------------------------------------------------
Filas totales: 57

    anio    departamento  casos_desnutricion  casos_vif
0   2019    Sacatepéquez                   0          1
1   2021  Quetzaltenango                   0          1
2   2021      Retalhuleu                   0          1
3   2022    Alta Verapaz                   0          2
4   2022   Chimaltenango                   0          2
5   2022     El Progreso                   0          1
6   2022       Guatemala                   0          1
7   2022   Huehuetenango                   0          2
8   2022         Jutiapa                   0          1
9   2022          Quiché                   0          2
10  2022    Sacatepéquez                   0          1
11  2023    Alta Verapaz                   0         86
12  2023    Baja Verapaz                   0         17
13  2023   Chimaltenango                   0         33
14  2023      Chiquimula                   0          4
15  2023     El Progreso                   0         19
16  2023       Escuintla                   0         18
17  2023       Guatemala                   0         49
18  2023   Huehuetenango                   0         12
19  2023          Izabal                   0          6
20  2023          Jalapa                   0          8
21  2023         Jutiapa                   0         17
22  2023           Petén                   0          9
23  2023  Quetzaltenango                   0         18
24  2023          Quiché                   0         23
25  2023      Retalhuleu                   0         23
26  2023    Sacatepéquez                   0         29
27  2023      San Marcos                   0         34
28  2023      Santa Rosa                   0         15
29  2023          Sololá                   0         17
30  2023   Suchitepéquez                   0         23
31  2023     Totonicapán                   0          7
32  2023          Zacapa                   0         16
33  2024    Alta Verapaz                   0         85
34  2024    Baja Verapaz                   0         20
35  2024   Chimaltenango                   0         26
36  2024      Chiquimula                   0          3
37  2024     El Progreso                   0         36
38  2024       Escuintla                   0         14
39  2024       Guatemala                   0         53
40  2024   Huehuetenango                   0         13
41  2024          Izabal                   0         11
42  2024          Jalapa                   0          9
43  2024         Jutiapa                   0         27
44  2024           Petén                   0         10
45  2024  Quetzaltenango                   0         18
46  2024          Quiché                   0         15
47  2024      Retalhuleu                   0         27
48  2024    Sacatepéquez                   0         33
49  2024      San Marcos                   0         25
50  2024      Santa Rosa                   0          7
51  2024          Sololá                   0          4
52  2024   Suchitepéquez                   0         21
53  2024     Totonicapán                   0         11
54  2024          Zacapa                   0         18
55  2026    Alta Verapaz                   0          4
56  2026       Guatemala                   0          5

25) PARCIAL: Top 5 municipios Chagas+Zika+Chikungunya combinados
----------------------------------------------------------------
Sin datos para mostrar.

26) PARCIAL: Vectores vs urbanizacion por departamento
------------------------------------------------------
Sin datos para mostrar.

27) PARCIAL: Tasa de morbilidad materna infantil por anio/departamento
----------------------------------------------------------------------
Sin datos para mostrar.

28) PARCIAL: Correlacion desnutricion y hechos delictivos por municipio
   Esta salida deja la serie lista para calcular correlacion fuera de SQL.
--------------------------------------------------------------------------------------------------------------------------------------------------
Filas totales: 1676

,anio,departamento,municipio,casos_desnutricion,hechos_delictivos
0,1962,Guatemala,Mixco,0,1
1,1967,Chiquimula,Chiquimula,0,2
2,1972,Guatemala,Guatemala,0,1
3,1980,Jutiapa,Yupiltepeque,0,2
4,1984,Quiché,Chajul,0,3
...,...,...,...,...,...
195,2010,Jalapa,Jalapa,0,84
196,2010,Jalapa,San Luis Jilotepeque,0,2
197,2010,Jutiapa,Jutiapa,0,37
198,2010,Jutiapa,Quesada,0,6
199,2010,Petén,Flores,0,81

Mostrando primeras 200 filas de 1676.

29) LISTA/PARCIAL: Violencia estructural urbano vs rural
--------------------------------------------------------
Filas totales: 16

    anio area_geografica  total_casos
0   2016          Urbano           22
1   2016        SIN_AREA            3
2   2017          Urbano           22
3   2017        SIN_AREA            2
4   2018          Urbano           18
5   2018           Rural            2
6   2018        SIN_AREA            2
7   2019          Urbano           18
8   2019           Rural            1
9   2019        SIN_AREA            1
10  2020          Urbano            6
11  2020           Rural            1
12  2021          Urbano            5
13  2021        SIN_AREA            1
14  2022          Urbano            7
15  2023          Urbano            2

30) LISTA/PARCIAL: Frecuencia de exhumaciones por tipo de delito relacionado
----------------------------------------------------------------------------
Sin datos para mostrar.